name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install requests

      - name: Train Model
        run: python train_model.py

      - name: Test UI
        run: echo "Skipped UI test in CI for now."

      - name: Build Docker Image
        run: docker build -t iris-ui-app .
